アラート実装
Hikari-Tanaka-pikka/hikari-frontend-basic-2022-todoapp pull request #11
Opened 2023-05-11 14:42 UTC by Hikari-Tanaka-pikka

2023-05-18 05:00 UTC, KEISUKE0293 reviewed
良いと思いますが、可能であれば以下の修正をお願いします！

2023-05-18 05:00 UTC, KEISUKE0293 commented on src/contexts/alert_handler.jsx
> +    setAlertState({ isActive: false, errorText: "" });
アラートが閉じる際にテキストが消えているので修正してください！

2023-05-19 16:46 UTC, higashiji2000 approved these changes
ほとんどいい感じです！
消えるときにテキストがからになる問題だけ確認お願いします！

2023-05-19 16:46 UTC, higashiji2000 commented on src/contexts/alert_handler.jsx
> +    setAlertState({ isActive: false, errorText: "" });
```suggestion
    setAlertState({ ...alertState, isActive: false });
```

もしくは

```suggestion
    setAlertState({ isActive: false, errorText: alertState.errorText });
```

こうすると以前のerrorテキストは現在のままで、isActiveだけ更新することができると思います。

2023-05-19 16:46 UTC, higashiji2000 requested changes
間違えてapproveしました🙏

2023-05-20 05:20 UTC, Hikari-Tanaka-pikka commented on src/contexts/alert_handler.jsx
> +    setAlertState({ isActive: false, errorText: "" });
@higashiji2000 
提案ありがとうございます!
修正しました!

2023-05-22 06:52 UTC, higashiji2000 reviewed
github pages で確認したいので、[こちら](https://playground.wraptas.site/35aeda2024434ac993fe827635ae7925)を参考にリポジトリの設定を変更し、生成したgithub pagesのリンクを教えてください！

2023-05-22 06:52 UTC, higashiji2000 commented on src/contexts/alert_handler.jsx
> +  };
```suggestion
  const closeAlert = () => {
    setAlertState({ isActive: false, alertMessage: alertState.alertMessage });
  };
```
変数名が違ったようです:pray:

2023-05-22 06:52 UTC, higashiji2000 commented on src/components/Organisms/AlertManager/index.jsx
> +  useEffect(() => {
```suggestion
const AlertManager = () => {
  const alertHandlerContext = useAlertHandlerContext();
  useEffect(() => {
```
`useContext` の返り値は単なるオブジェクトなので、ローワーキャメルケースが適切かと思います。

2023-05-24 02:40 UTC, Hikari-Tanaka-pikka commented on src/contexts/alert_handler.jsx
> +  };
@higashiji2000 

対応しました!

2023-05-24 02:40 UTC, Hikari-Tanaka-pikka commented on src/components/Organisms/AlertManager/index.jsx
> +  useEffect(() => {
@higashiji2000 
対応しました!

2023-05-25 13:59 UTC, Higashiji commented on src/components/Organisms/AlertManager/index.jsx
> +  useEffect(() => {
コードの他の部分がアッパーキャメルケースのままのようで、エラーが出ています。
修正お願いします！

2023-05-25 14:01 UTC, higashiji2000 requested changes
github pagesがまだエラーになっているので、[こちら](https://playground.wraptas.site/35aeda2024434ac993fe827635ae7925)を再度確認お願いします。
解決が難しそうであれば教えてください！

また、完了したらgithub pagesのリンクをPRのコメントで貼ってください🛸

2023-05-28 03:49 UTC, higashiji2000 commented
![image](https://github.com/Hikari-Tanaka-pikka/hikari-frontend-basic-2022-todoapp/assets/83479175/88c735c5-dc31-4956-9fec-0c7aded3c1fe)

[こちら](https://github.com/Hikari-Tanaka-pikka/hikari-frontend-basic-2022-todoapp/pull/11#discussion_r1205564549)のコメントの内容を修正後再度試してみてください！

2023-05-29 02:23 UTC, higashiji2000 approved these changes
LGTMです 🥇

2023-05-29 11:59 UTC, merged